name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request: {}

jobs:
  build:
    strategy:
      matrix:
        dc: [dmd-latest, ldc-latest]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: mihails-strasuns/setup-dlang@v0.5.0
      with:
        compiler: ${{ matrix.dc }}
    - name: Run tests
      run: dub -q test
