name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request: {}

jobs:
  info:
    runs-on: ubuntu-latest
    outputs:
      has_tag: ${{ steps.get_info.outputs.has_tag }}
      tag: ${{ steps.get_info.outputs.tag }}
    steps:
      - id: get_info
        run: |
          tag="${REF##*/}"
          echo "::set-output name=has_tag::$has_tag"
          echo "::set-output name=tag::$tag"
        env:
          REF: ${{ github.ref }}
          has_tag: ${{ startsWith(github.ref, 'refs/tags/') }}

  test:
    strategy:
      matrix:
        dc: [dmd-latest, ldc-latest]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/cache@v2
        with:
          path: ~/.dub
          key: ${{ runner.os }}-dub-${{ hashFiles('**/dub.json') }}
          restore-keys: |
            ${{ runner.os }}-dub-
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Run tests
        run: dub -q test
      - name: Run examples
        run: ./test_examples.sh

  release:
    runs-on: ubuntu-latest
    needs: [info, test]
    if: github.event_name == 'push' && needs.info.outputs.has_tag == 'true'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build a package
        run: |
          docker run --rm -i -v ${GITHUB_WORKSPACE}:/workdir -w /workdir alpine:${alpineVersion} sh alpine-build.sh
          cd ${GITHUB_WORKSPACE}/bin
          tar cf ${GITHUB_WORKSPACE}/medal.tar.gz medal
        env:
          alpineVersion: 3.12
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/medal.tar.gz
          asset_name: medal-linux-x86_64.tar.gz
          asset_content_type: application/tar+gzip
