name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request: {}

jobs:
  build:
    strategy:
      matrix:
        dc: [dmd-latest, ldc-latest]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.dub
        key: ${{ runner.os }}-dub-${{ hashFiles('**/dub.json') }}
        restore-keys: |
          ${{ runner.os }}-dub-
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}
    - name: Run tests
      run: dub -q test
    - name: Run examples
      run: ./test_examples.sh
